apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: confluent-platform-cp-kafka-connect-ingress
  namespace: confluent-platform
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: subnet-081f93ed9aa680786,subnet-02086c09e2d9eb61d
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: confluent-platform-cp-kafka-connect
                port:
                  name: kafka-connect