apiVersion: v1
kind: ConfigMap
metadata:
  name: kipu-debezium-configmap
  labels:
    app: {{ template "cp-kafka-connect.name" . }}
    chart: {{ template "cp-kafka-connect.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  kipu-debezium.zip: custom-plugins/debezium-source-plugin.zip
