apiVersion: v1
kind: ConfigMap
metadata:
  name: merge-plugins-script
  labels:
    app: {{ template "cp-kafka-connect.name" . }}
    chart: {{ template "cp-kafka-connect.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  merge-script.sh: |
    #!/bin/sh

    echo "Merging custom plugins into Kafka Connect plugins directory"

    apt-get update -y && apt-get upgrade -y
    apt-get install -y curl

    mkdir -p /plugins/kipu-debezium-postgres/lib

    curl -o /plugins/kipu-debezium-postgres/lib/debezium-api-2.0.0-SNAPSHOT.jar https://kipu-wiki.s3.amazonaws.com/test-plugin/debezium-api-2.0.0-SNAPSHOT.jar
    curl -o /plugins/kipu-debezium-postgres/lib/debezium-connector-postgres-2.0.0-SNAPSHOT.jar https://kipu-wiki.s3.amazonaws.com/test-plugin/debezium-connector-postgres-2.0.0-SNAPSHOT.jar
    curl -o /plugins/kipu-debezium-postgres/lib/debezium-core-2.0.0-SNAPSHOT.jar https://kipu-wiki.s3.amazonaws.com/test-plugin/debezium-core-2.0.0-SNAPSHOT.jar
    curl -o /plugins/kipu-debezium-postgres/lib/connect-transforms-0.1.1.jar https://kipu-wiki.s3.amazonaws.com/test-plugin/connect-transforms-0.1.1.jar
    curl -o /plugins/kipu-debezium-postgres/lib/connect-transforms-1.4.2.jar https://kipu-wiki.s3.amazonaws.com/test-plugin/connect-transforms-1.4.2.jar
    curl -o /plugins/kipu-debezium-postgres/lib/postgresql-42.3.3.jar https://kipu-wiki.s3.amazonaws.com/test-plugin/postgresql-42.3.3.jar
    curl -o /plugins/kipu-debezium-postgres/lib/connect-utils-0.1.0.jar https://kipu-wiki.s3.amazonaws.com/test-plugin/connect-utils-0.1.0.jar
    curl -o /plugins/kipu-debezium-postgres/lib/kafka-connect-jdbc-10.4.1.jar https://kipu-wiki.s3.amazonaws.com/test-plugin/kafka-connect-jdbc-10.4.1.jar
    
    echo "Done merging custom plugins into Kafka Connect plugins directory"

    echo "Setting permissions on Kafka Connect plugins directory"
    chwon -R appuser:appuser /plugins/kipu-debezium-postgres

    echo "Listing contents of Kafka Connect plugins directory"
    ls -l /plugins
